#EasyKeyBinder Configuration File

#Key Binding
binding:
  #Key Binding for "SHIFT + F"
  shiftF:
    enable: false
    command: ""
    permission: true
  #Key Binding for "SHIFT + Q"
  shiftQ:
    enable: false
    command: ""
    permission: true

#Lang Section:
lang:
  prefix: "EKB// "
  permission-denied: "You do not have enough permission to perform this action"
  reload: "Configuration Successfully reloaded"

