name: EasyKeyBinder
version: 'Alpha-1.0'
main: com.hypernite.plugin.os.easykeybinder.main.EasyKeyBinder
api-version: 1.16
authors: [ AnsonTsang ]
website: https://www.hypernite.com
commands:
  ekb-reload:
    description: reload plugin