name: 'Build Jar And Publish'

on:
  push:
    branches: [ master ]

jobs:
  build_jar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: eric2788/maven-jar-publish@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        java-version: 8
        body: 'for minecraft 1.16.5'